// 100 kata lazim Indonesia (KBBI), pola: konsonan-vokal-konsonan-vokal
export const words: Array<[string, string]> = [
  ['bu', 'ku'],
  ['ba', 'lu'],
  ['ba', 'tu'],
  ['ba', 'si'],
  ['bi', 'sa'],
  ['ba', 'ta'],
  ['ci', 'ri'],
  ['cu', 'mi'],
  ['co', 'ba'],
  ['ca', 'ri'],
  ['da', 'da'],
  ['da', 'ta'],
  ['di', 'ni'],
  ['do', 'sa'],
  ['da', 'du'],
  ['so', 'fa'],
  ['gi', 'gi'],
  ['gu', 'la'],
  ['gi', 'la'],
  ['ga', 'ji'],
  ['ti', 'ga'],
  ['ha', 'ti'],
  ['ho', 'bi'],
  ['ha', 'ri'],
  ['ba', 'ru'],
  ['ku', 'ra'],
  ['ta', 'mu'],
  ['ka', 'ca'],
  ['ja', 'ri'],
  ['ja', 'ga'],
  ['ja', 'mu'],
  ['ju', 'ru'],
  ['ka', 'ki'],
  ['ku', 'da'],
  ['ko', 'ta'],
  ['ka', 'ca'],
  ['ka', 'li'],
  ['ke', 'ra'],
  ['la', 'lu'],
  ['lu', 'pa'],
  ['la', 'ba'],
  ['la', 'ma'],
  ['ma', 'ma'],
  ['ma', 'ta'],
  ['mi', 'si'],
  ['ma', 'sa'],
  ['na', 'si'],
  ['na', 'da'],
  ['na', 'la'],
  ['pa', 'di'],
  ['pa', 'lu'],
  ['pa', 'gi'],
  ['pi', 'pa'],
  ['ra', 'sa'],
  ['ra', 'tu'],
  ['ri', 'bu'],
  ['ra', 'sa'],
  ['ri', 'ba'],
  ['ro', 'ti'],
  ['sa', 'pi'],
  ['sa', 'tu'],
  ['su', 'ka'],
  ['si', 'si'],
  ['si', 'ra'],
  ['ta', 'li'],
  ['ta', 'mu'],
  ['ta', 'ta'],
  ['ta', 'ri'],
  ['tu', 'na'],
  ['ta', 'hu'],
  ['vi', 'la'],
  ['yo', 'yo'],
  ['wu', 'du'],
];

export const getRandomWord = (): [string, string] => {
  const randomIndex = Math.floor(Math.random() * words.length);
  return words[randomIndex];
};

export const generateSyllables = (targetSyllable: string): string[] => {
  const firstLetter = targetSyllable.charAt(0);
  return 'aiueo'.split('').map(vowel => `${firstLetter}${vowel}`);
};
